spring:
  application:
    name: zuul
server:
  port: 8090
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  prefix: /api
  routes:
    ms-barrios:
      path: /barrios/**
      stripPrefix: true
    ms-districts:
      path: /distritos/**
      stripPrefix: true
    users:
      path: /usuarios/**
      stripPrefix: true
    oauth:
      path: /security/**
      stripPrefix: true
      sensitive-headers:
      - Cookie , Set-Cookie