spring:
  application:
    name: servicio-zuul
server:
  port: 8090
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul:
  prefix: /api
  routes:
    servicio-categorias:
      path: /categories/**
      stripPrefix: true   
    servicio-languages:
      path: /languages/**
      stripPrefix: true
    servicio-usuarios:
      path: /usuarios/**
      stripPrefix: true
    servicio-oauth:
      path: /security/**
      stripPrefix: true
      sensitive-headers:
      - Cookie , Set-Cookie     
    servicio-internationalization:
     path: /internationalization/**
     stripPrefix: true
    servicio-blogs:
     path: /blogs/**
     stripPrefix: true
    servicio-comentarios:
     path: /comentarios/**
     stripPrefix: true
    servicio-newsletter:
     path: /newsletter/**
     stripPrefix: true